### ISSUE TITLE
All lookups fail in ~1s between database expiring & updating.

### ISSUE THREAD

**Issue by cpu** [google/safebrowsing#69]
Hi again folks :wave:

First-off: Thanks again for the great library! We've been using it in production for Let's Encrypt since the end of July and it has suited our needs perfectly! Kudos to the team working on this and the folks behind the scenes :-) We really appreciate your work!

I've noticed in the past few days that there appears to be a small window between when `*database.Status()` marks the DB stale and when the database is updated in which all lookups will fail due to the DB being marked stale with messages like:
> inconsistent database: safebrowsing: threat list is stale

Here is one concrete example from our logs:
```
2017-08-13T21:26:38.571064+00:00 safebrowsing: 2017/08/13 21:26:38 safebrowser.go:537: background threat list updated
2017-08-13T21:26:38.571408+00:00 safebrowsing: 2017/08/13 21:26:38 safebrowser.go:532: Next update in 30m29.012s
2017-08-13T21:57:09.490334+00:00 safebrowsing: 2017/08/13 21:57:09 safebrowser.go:400: inconsistent database: safebrowsing: threat list is stale
<snipped a bunch of occurences>
2017-08-13T21:57:09.797071+00:00 safebrowsing: 2017/08/13 21:57:09 safebrowser.go:400: inconsistent database: safebrowsing: threat list is stale
2017-08-13T21:57:10.283417+00:00 safebrowsing: 2017/08/13 21:57:10 safebrowser.go:537: background threat list updated
```

In one case we saw ~422 lookups fail within the ~1 second window between the database being marked stale and updating. Eek!

The point at which the database is next scheduled to be updated after a successful update is computed in [`*database.Update()`](https://github.com/google/safebrowsing/blob/6af285eb0adbbfb570cc0a80989024f026ab8ca6/database.go#L235:L243) by adding `db.configUpdatePeriod` to `time.Duration(rand.Int31n(60)-30)*time.Second`.  It looks like [`*database.Status()`](https://github.com/google/safebrowsing/blob/6af285eb0adbbfb570cc0a80989024f026ab8ca6/database.go#L154:L157) decides if the DB is stale by comparing `now().Sub(db.last)` with `(db.config.UpdatePeriod + jitter)`. In this case `jitter` is always a fixed `30 * time.Second`.

It seems like this strategy doesn't offer enough grace time to account for having to update the database. Especially if we imagine that the initial database update request may fail and a backoff would occur.

Is it possible to schedule the database update ahead of the point at which it will expire by a larger grace period (e.g. 5m?). I believe this would minimize the chances that lookups would fail due to an out-of-date database that is microseconds away from being updated. I'm open to other work arounds as well!

Thanks again,

**Comment by cpu** [comment]
I suppose one option is to check `*database.Ready()` before issuing Lookups but I think having the database consistent more often by planning the update with enough grace is better than holding for the consistency.

**Comment by colonelxc** [comment]
Yeah, I definitely think a longer staleness threshold is warranted. Double
the default refresh period makes sense to me. It would allow one update
retry in case of failure, before being marked stale.

The full hash confirmation will still help exclude matches that have been
removed from the blacklists. It just won't have some of the latest
blacklist items.

I'm out on vacation at the moment, so maybe someone else can help get this
resolved (or I'll be back next week).

**Comment by cpu** [comment]
> Yeah, I definitely think a longer staleness threshold is warranted. Double the default refresh period makes sense to me. It would allow one update retry in case of failure, before being marked stale.

Sounds good to me.

>  I'm out on vacation at the moment, so maybe someone else can help get this resolved (or I'll be back next week).

I can take a crack submitting a PR for the above if it sounds reasonable. Enjoy your vacation!!! :beach_umbrella: :tropical_drink:

**Comment by nimbleo** [comment]
So, what colonelxc means is that we double DefaultUpdatePeriod? I guess then we still have the same issue since update period and staleness check condition are synchronized again. Or, do you mean we double the jitter in the staleness check condition (i.e., > UpdatePeriod + 2*jitter) ?

**Comment by colonelxc** [comment]
Basically to make the staleness check to be 60 minutes (2*default update
time).

**Comment by cpu** [comment]
> I can take a crack submitting a PR for the above if it sounds reasonable. Enjoy your vacation!!! :beach_umbrella: :tropical_drink:

As promised here's a PR implementing the staleness check change that colonelxc mentioned: https://github.com/google/safebrowsing/pull/70
